declare const switchTheme: HTMLDivElement;
declare const lightMode: HTMLDivElement;
declare const darkMode: HTMLDivElement;
declare let isLight: boolean;
declare function toggleTheme(): void;
declare const input: HTMLInputElement;
declare const workerCountPicker: HTMLInputElement;
declare const thresholdPicker: HTMLInputElement;
declare const resultsFooter: HTMLDivElement;
declare const progressBar: HTMLProgressElement;
declare const currentlyProcessing: HTMLDivElement;
declare const resultSummary: HTMLDivElement;
declare const resultText: HTMLParagraphElement;
declare const resultCode: HTMLPreElement;
declare const resultPanel: HTMLDivElement;
declare function chunks(array: any, parts: any): any[];
declare let neededResults: number;
declare const results: any[];
